### ISSUE TITLE
Flaky tests on iOS 10.3 in Saucelabs

### ISSUE THREAD

**Issue by web-padawan** [vaadin/vaadin-grid#1713]
### Description

The following tests are flaky and cause (apparently) random failures on iOS 10.3:

```
iOS Simulator iphone 10.3 ✖ test/light-dom-observing.html » light dom observing » dom-repeat » groups inside group » should remove cell content
  Script error. (:0)
iOS Simulator iphone 10.3 Tests failed: Error thrown outside of test function: undefined is not an object (evaluating 'fn.call')
```

```
iOS Simulator iphone 10.3 ✖ test/light-dom-observing.html » light dom observing » dom-repeat » columns inside group » should remove columns late
  undefined is not an object (evaluating 'this._grid.__updateHeaderFooterRowVisibility')
                   _pathOrHeaderChanged at /components/ at vaadin/[secure]/src/[secure]-column.js:363:0
                  runEffectsForProperty at /components/ at polymer/polymer/lib/mixins/property-effects.js:168:0
                             runEffects at /components/ at polymer/polymer/lib/mixins/property-effects.js:128:0
                     _propertiesChanged at /components/ at polymer/polymer/lib/mixins/property-effects.js:1909:0
                       _flushProperties at /components/ at polymer/polymer/lib/mixins/properties-changed.js:400:0
                       _flushProperties at /components/ at polymer/polymer/lib/mixins/property-effects.js:1737:0
                  _invalidateProperties at /components/ at polymer/polymer/lib/mixins/property-effects.js:1703:0
                             notifyPath at /components/ at polymer/polymer/lib/mixins/property-effects.js:2323:0
                                   <unknown> at   http://localhost:8081/components/ at vaadin/[secure]/src/[secure].js:553:0
                             _updateRow at /components/ at vaadin/[secure]/src/[secure].js:512:0
                      _renderColumnTree at /components/ at vaadin/[secure]/src/[secure].js:686:0
                                   <unknown> at   http://localhost:8081/components/ at vaadin/[secure]/src/[secure]-column.js:464:0
                                   <unknown> at   http://localhost:8081/components/ at polymer/polymer/lib/utils/debounce.js:46:0
```

**Comment by web-padawan** [comment]
There are some tests failing also on iOS 12 😞 

```
iOS Simulator iphone 12.2 ✖ test/light-dom-observing.html » light dom observing » dom-repeat » columns inside group » should add columns late
  undefined is not an object (evaluating 'this._grid.__updateHeaderFooterRowVisibility')
                   _pathOrHeaderChanged at /components/ at vaadin/[secure]/src/[secure]-column.js:361:0
                  runEffectsForProperty at /components/ at polymer/polymer/lib/mixins/property-effects.js:168:0
                             runEffects at /components/ at polymer/polymer/lib/mixins/property-effects.js:128:0
                     _propertiesChanged at /components/ at polymer/polymer/lib/mixins/property-effects.js:1909:0
                       _flushProperties at /components/ at polymer/polymer/lib/mixins/properties-changed.js:396:0
                       _flushProperties at /components/ at polymer/polymer/lib/mixins/property-effects.js:1737:0
                  _invalidateProperties at /components/ at polymer/polymer/lib/mixins/property-effects.js:1703:0
                             notifyPath at /components/ at polymer/polymer/lib/mixins/property-effects.js:2323:0
                                   <unknown> at   http://localhost:8081/components/ at vaadin/[secure]/src/[secure].js:573:0
                             _updateRow at /components/ at vaadin/[secure]/src/[secure].js:532:0
                      _renderColumnTree at /components/ at vaadin/[secure]/src/[secure].js:706:0
                                   <unknown> at   http://localhost:8081/components/ at vaadin/[secure]/src/[secure]-column.js:462:0
                                   <unknown> at   http://localhost:8081/components/ at polymer/polymer/lib/utils/debounce.js:41:0
```

```
iOS Simulator iphone 12.2 ✖ test/light-dom-observing.html » light dom observing » dom-repeat » groups inside grid » should add columns late
  expected '' to include 'grid repeats group d header'
    <unknown> at            AssertionError at /components/chai/chai.js:5260:0
    <unknown> at                    assert at /components/chai/chai.js:259:0
    <unknown> at                   include at /components/chai/chai.js:557:0
    <unknown> at                    assert at /components/chai/chai.js:3829:0
    <unknown> at   expectFirstColumnHeader at light-dom-observing.html:400:0
    <unknown> at         expectFirstColumn at light-dom-observing.html:416:0
    <unknown> at                 <unknown> at light-dom-observing.html:598:0
    <unknown> at                      done at /components/wct-browser-legacy/browser.js:129:0
```
