### ISSUE TITLE
Connector can only be initialized for an attached Grid

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-grid#1828]
Sometimes (still not sure how to replicate) when navigating in-app back to a page with a Grid, this exception is thrown and the client freezes (blue loading bar stuck):

```
java.lang.IllegalStateException: Connector can only be initialized for an attached Grid
        com.vaadin.flow.component.grid.Grid.lambda$initConnector$4(Grid.java:1347)
```

This started happening after updating from V14 to V16.

**Comment by Gedankendreher** [comment]
I have an overview grid where I can edit details of a row. This is implemented in a kind of stack. As soon as the user presses "edit" for a row, the current view is removed from the parent container via removeall() and the detail editor is added instead. Once this is completed, the detail is removed (with removeAll on parent container again). Finally, the view with the grid is attached again via add(). This works as expected unless drag and drop is used. It doesn't matter if the grid itself is created again as part of "onAttach". 

My steps to reproduce this:

1. Create Grid of any type
2. add drag and drop listeners so you can move rows up- and downwards
3. move a row up or down (important step, this triggers the error)
4. temporarily change view (I use to edit details of a row)
5. restore view with grid

This results in the following exception:
`java.lang.IllegalStateException: Connector can only be initialized for an attached Grid
        at com.vaadin.flow.component.grid.Grid.lambda$initConnector$4(Grid.java:1375) ~[vaadin-grid-flow-14.5.2.jar:?]
        at java.util.Optional.orElseThrow(Optional.java:408) ~[?:?]
        at com.vaadin.flow.component.grid.Grid.initConnector(Grid.java:1375) ~[vaadin-grid-flow-14.5.2.jar:?]
        at com.vaadin.flow.component.grid.Grid$GridArrayUpdaterImpl.initialize(Grid.java:1125) ~[vaadin-grid-flow-14.5.2.jar:?]
        at com.vaadin.flow.data.provider.DataCommunicator.lambda$requestFlush$2f364bb9$1(DataCommunicator.java:423) ~[flow-data-2.5.2.jar:2.5.2]
        at com.vaadin.flow.internal.StateTree.lambda$runExecutionsBeforeClientResponse$2(StateTree.java:390) ~[flow-server-2.5.2.jar:2.5.2]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?]
        at com.vaadin.flow.internal.StateTree.runExecutionsBeforeClientResponse(StateTree.java:387) ~[flow-server-2.5.2.jar:2.5.2]
        at com.vaadin.flow.server.communication.UidlWriter.encodeChanges(UidlWriter.java:411) ~[flow-server-2.5.2.jar:2.5.2]
        at com.vaadin.flow.server.communication.UidlWriter.createUidl(UidlWriter.java:187) ~[flow-server-2.5.2.jar:2.5.2]
        at com.vaadin.flow.server.communication.UidlRequestHandler.writeUidl(UidlRequestHandler.java:122) ~[flow-server-2.5.2.jar:2.5.2]
        at com.vaadin.flow.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:91) ~[flow-server-2.5.2.jar:2.5.2]
        at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40) ~[flow-server-2.5.2.jar:2.5.2]
        at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1547) [flow-server-2.5.2.jar:2.5.2]
        at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:247) [flow-server-2.5.2.jar:2.5.2]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:733) [tomcat9-servlet-api.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat9-catalina-9.0.39.jar:9.0.39]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat9-catalina-9.0.39.jar:9.0.39]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat9-websocket-9.0.39.jar:9.0.39]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat9-catalina-9.0.39.jar:9.0.39]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat9-catalina-9.0.39.jar:9.0.39]
        at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126) [tomcat9-catalina-9.0.39.jar:9.0.39]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat9-catalina-9.0.39.jar:9.0.39]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat9-catalina-9.0.39.jar:9.0.39]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [tomcat9-catalina-9.0.39.jar:9.0.39]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) [tomcat9-catalina-9.0.39.jar:9.0.39]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) [tomcat9-catalina-9.0.39.jar:9.0.39]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143) [tomcat9-catalina-9.0.39.jar:9.0.39]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat9-catalina-9.0.39.jar:9.0.39]
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690) [tomcat9-catalina-9.0.39.jar:9.0.39]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [tomcat9-catalina-9.0.39.jar:9.0.39]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat9-catalina-9.0.39.jar:9.0.39]
        at org.apache.coyote.http2.StreamProcessor.service(StreamProcessor.java:395) [tomcat9-coyote-9.0.39.jar:9.0.39]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat9-coyote-9.0.39.jar:9.0.39]
        at org.apache.coyote.http2.StreamProcessor.process(StreamProcessor.java:73) [tomcat9-coyote-9.0.39.jar:9.0.39]
        at org.apache.coyote.http2.StreamRunnable.run(StreamRunnable.java:35) [tomcat9-coyote-9.0.39.jar:9.0.39]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat9-util-9.0.39.jar:9.0.39]
        at java.lang.Thread.run(Thread.java:834) [?:?]`
