### ISSUE TITLE
Grid throws UnsupportedOperationException if buffered editor is open

### ISSUE THREAD

**Issue by robert-lee-hisl** [vaadin/vaadin-grid#1912]
Exception stacktrace begins:

```
ERROR [com.vaadin.flow.server.DefaultErrorHandler] (default task-19) : java.lang.UnsupportedOperationException: Buffered editor should be closed using save() or cancel()
        at com.vaadin.flow.component.grid.editor.EditorImpl.closeEditor(EditorImpl.java:124)
        at com.vaadin.flow.component.grid.Grid.onDataProviderChange(Grid.java:3382)
        at com.vaadin.flow.component.grid.Grid.lambda$handleDataProviderChange$78e8296$1(Grid.java:3425)
```

I saw this when calling refreshItem() on TreeGrid after adding a child item; refreshItem() seems to fire a dataprovider event and no check is done to see if the editor is buffered or not. 

IMHO, the editor should cancel instead of saving in this case, because saving might fail due to validation.

**Comment by paodb** [comment]
Hello. I'm working on Vaadin version 14.5.2 and I see this behavior on Grid when using @PreserveOnRefresh annotation. If I do refresh while editing a row, then I get the same error: 

```java
java.lang.UnsupportedOperationException: Buffered editor should be closed using save() or cancel()
	at com.vaadin.flow.component.grid.editor.EditorImpl.closeEditor(EditorImpl.java:124 undefined) ~[vaadin-grid-flow-14.5.2.jar:na]
	at com.vaadin.flow.component.grid.Grid.onDataProviderChange(Grid.java:3538 undefined) ~[vaadin-grid-flow-14.5.2.jar:na]
	at com.vaadin.flow.component.grid.Grid.handleDataProviderChange(Grid.java:3574 undefined) ~[vaadin-grid-flow-14.5.2.jar:na]
	at com.vaadin.flow.component.grid.Grid.onAttach(Grid.java:3054 undefined) ~[vaadin-grid-flow-14.5.2.jar:na]
	at com.vaadin.flow.component.ComponentUtil.onComponentAttach(ComponentUtil.java:231 undefined) ~[flow-server-2.5.2.jar:2.5.2]
	at com.vaadin.flow.internal.nodefeature.ComponentMapping.lambda$onAttach$0(ComponentMapping.java:102 undefined) ~[flow-server-2.5.2.jar:2.5.2]
	at java.util.Optional.ifPresent(Optional.java:159 undefined) ~[na:1.8.0_251]
```
Here's a little example to reproduce this:

```java
@PreserveOnRefresh
@Route("")
public class TestView extends HorizontalLayout {
	
    public TestView() {
    	// grid
    	Grid<Person> grid = new Grid<>();
    	List<Person> gridItems = new PersonService().fetch(0, 5);
    	grid.setItems(gridItems);
    	Column<Person> firstNameColumn = grid.addColumn(Person::getFirstName).setHeader("First Name");
    	grid.addColumn(Person::getLastName).setHeader("Last Name");
    	
    	// define editor & binder for editor
    	Binder<Person> binder = new Binder<>(Person.class);
		Editor<Person> editor = grid.getEditor();
		editor.setBinder(binder);
		editor.setBuffered(true);
		
    	// define editor components for columns
        TextField firstNameField = new TextField();
        binder.bind(firstNameField, Person::getFirstName, Person::setFirstName);
        firstNameColumn.setEditorComponent(firstNameField);
               
        // call edit
        grid.addItemDoubleClickListener(event -> {
            grid.getEditor().editItem(event.getItem());
            firstNameField.focus();
        });
    	
        add(grid);
    }
}
```
