### ISSUE TITLE
Grid - DataProvider throws Exception when Size changes 

### ISSUE THREAD

**Issue by neerup** [vaadin/vaadin-grid#1940]
In Vaadin 14 RC4 Grid throws an Exception when size callback returns a larger number than the initial call returned... 
In Vaadin 8 this worked fine.
How can the size change? you might ask
Because all DataProviders require a Size and our backend does not support a size method. We have to hack the DataProvider a bit, the way we have done this since Vaadin 7 is to return a fixed number like 50 in the size callback the first time. if the there is only 10 records we only return the 10 records and the size callback is called again, now we know there is only 10 so 10 is returned. This still works fine... The other scenario where it turns out that there is more than 50 rows, we leave out the 50th record when requested, this triggers a call to size callback now we return 50+50 until the end is reached we return the correct number of records. This has worked fine until Vaadin 14, where it Throws an Exception:
`15/07 15:28:07:578 ERROR com.vaadin.flow.server.DefaultErrorHandler - 
java.lang.IndexOutOfBoundsException: Index: 79, Size: 79
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at com.vaadin.flow.data.provider.DataCommunicator.lambda$getJsonItems$3(DataCommunicator.java:611)
	at java.util.stream.IntPipeline$4$1.accept(IntPipeline.java:250)
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.vaadin.flow.data.provider.DataCommunicator.getJsonItems(DataCommunicator.java:613)
	at com.vaadin.flow.data.provider.DataCommunicator.lambda$collectChangesToSend$2(DataCommunicator.java:571)
	at com.vaadin.flow.data.provider.DataCommunicator.applyIfNotEmpty(DataCommunicator.java:627)
	at com.vaadin.flow.data.provider.DataCommunicator.withMissing(DataCommunicator.java:621)
	at com.vaadin.flow.data.provider.DataCommunicator.collectChangesToSend(DataCommunicator.java:570)
	at com.vaadin.flow.data.provider.DataCommunicator.flush(DataCommunicator.java:473)
	at com.vaadin.flow.data.provider.DataCommunicator.lambda$requestFlush$2f364bb9$1(DataCommunicator.java:421)
	at com.vaadin.flow.internal.StateTree.lambda$runExecutionsBeforeClientResponse$1(StateTree.java:350)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.vaadin.flow.internal.StateTree.runExecutionsBeforeClientResponse(StateTree.java:347)
	at com.vaadin.flow.server.communication.UidlWriter.encodeChanges(UidlWriter.java:392)
	at com.vaadin.flow.server.communication.UidlWriter.createUidl(UidlWriter.java:182)
	at com.vaadin.flow.server.communication.UidlRequestHandler.writeUidl(UidlRequestHandler.java:116)
	at com.vaadin.flow.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:89)
	at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1540)
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:246)
`

**Comment by TatuLund** [comment]
This is duplicate of https://github.com/vaadin/vaadin-grid/issues/2038
