### ISSUE TITLE
MutliSelection - Hierarchical data provider doesn't support non-hierarchical queries

### ISSUE THREAD

**Issue by jm2rodriguez** [vaadin/vaadin-grid#1963]
The exception "Hierarchical data provider doesn't support non-hierarchical queries" is raised when selecting an item in the TreeGrid (multiselection mode) (Vaadin 12.0.7).

This error doesn't occurs when single selection mode is set.

`
public interface TestItem {

	public String getDescription();
	public String getNumber();
	public TestItem getParent();

}

public class TestItemStudy implements TestItem
...

public class TestItemSeries implements TestItem
...

public class TestView extends Div {
	...
	TestItemStudy studyS1 = new TestItemStudy("Magnetic Resonance");
	TestItemSeries series1S1 = new TestItemSeries("MRpoi", "101", studyS1);
	TestItemSeries series2S1 = new TestItemSeries("MRqwe", "102", studyS1);
	TestItemStudy studyS2 = new TestItemStudy("Ultrasound");
	TestItemSeries series1S2 = new TestItemSeries("Series USxyz", "201", studyS2);
	TestItemSeries series2S2 = new TestItemSeries("Series USabc", "202", studyS2);

	TreeData<TestItem> treeData;
	treeData = new TreeData<TestItem>();

	// Add root items
	treeData.addItem(studyS1.getParent(), studyS1);
	treeData.addItem(studyS2.getParent(), studyS2);

	// Add children items
	treeData.addItem(series1S1.getParent(), series1S1);
	treeData.addItem(series2S1.getParent(), series2S1);
	treeData.addItem(series1S2.getParent(), series1S2);
	treeData.addItem(series2S2.getParent(), series2S2);

	TreeDataProvider<TestItem> treeDataProvider;
	treeDataProvider = new TreeDataProvider<TestItem>(treeData);

	treeGrid = new TreeGrid<TestItem>();
	...
	treeGrid.setDataProvider(treeDataProvider);
	treeGrid.setSelectionMode(SelectionMode.MULTI);
	
	...
}
`

Exception raised
`
java.lang.RuntimeException: java.lang.IllegalArgumentException: Hierarchical data provider doesn't support non-hierarchical queries
	at com.vaadin.flow.server.communication.rpc.PublishedServerEventHandlerRpcHandler.invokeMethod(PublishedServerEventHandlerRpcHandler.java:174)
	at com.vaadin.flow.server.communication.rpc.PublishedServerEventHandlerRpcHandler.invokeMethod(PublishedServerEventHandlerRpcHandler.java:129)
	at com.vaadin.flow.server.communication.rpc.PublishedServerEventHandlerRpcHandler.handleNode(PublishedServerEventHandlerRpcHandler.java:117)
	at com.vaadin.flow.server.communication.rpc.AbstractRpcInvocationHandler.handle(AbstractRpcInvocationHandler.java:64)
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleInvocationData(ServerRpcHandler.java:379)
	at com.vaadin.flow.server.communication.ServerRpcHandler.lambda$handleInvocations$0(ServerRpcHandler.java:368)
	at java.util.ArrayList.forEach(ArrayList.java:1255)
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:368)
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:310)
	at com.vaadin.flow.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:89)
	at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1545)
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:227)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Hierarchical data provider doesn't support non-hierarchical queries
	at com.vaadin.flow.data.provider.hierarchy.HierarchicalDataProvider.size(HierarchicalDataProvider.java:53)
	at com.vaadin.flow.component.grid.AbstractGridMultiSelectionModel.selectFromClient(AbstractGridMultiSelectionModel.java:101)
	at com.vaadin.flow.component.grid.Grid.select(Grid.java:2513)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.flow.server.communication.rpc.PublishedServerEventHandlerRpcHandler.invokeMethod(PublishedServerEventHandlerRpcHandler.java:167)
	... 35 common frames omitted
`

**Comment by web-padawan** [comment]
Closing as duplicate of #1973
