### ISSUE TITLE
NPE related to sorting when recreating columns

### ISSUE THREAD

**Issue by vesanieminen** [vaadin/vaadin-grid#1969]
The following error happens if Grid columns have sorting enabled and the columns are recreated:

`Caused by: java.lang.IllegalArgumentException: Received a sorters changed call from the client for a non-existent column
	at com.vaadin.flow.component.grid.Grid.sortersChanged(Grid.java:2791)`

![Screen Shot 2019-05-15 at 10 44 44](https://user-images.githubusercontent.com/108755/57757615-7fd5ce80-76fe-11e9-8107-1d58ab1002d6.png)

Steps to reproduce:

1. git clone git@github.com:vesanieminen/Vaadin-Grid-recreate-columns-bug.git
2. mvn jetty:run
3. navigate to localhost:9997
4. click on the sorting buttons on the grid header for one of the columns
5. Select a different value from the Select component.

Expected behaviour:

- The Grid columns are recreated with no exceptions in the backend

Actual behaviour:

- The Grid columns are recreated with an exception.

Workaround exists here: https://github.com/vesanieminen/Vaadin-Grid-recreate-columns-bug/commit/100d56c352f23674e0fbe562878c4473a1e1d3bc

Full error log for the bug:

`[qtp1571205437-69] ERROR com.vaadin.flow.server.DefaultErrorHandler - 
java.lang.RuntimeException: java.lang.IllegalArgumentException: Received a sorters changed call from the client for a non-existent column
	at com.vaadin.flow.server.communication.rpc.PublishedServerEventHandlerRpcHandler.invokeMethod(PublishedServerEventHandlerRpcHandler.java:174)
	at com.vaadin.flow.server.communication.rpc.PublishedServerEventHandlerRpcHandler.invokeMethod(PublishedServerEventHandlerRpcHandler.java:129)
	at com.vaadin.flow.server.communication.rpc.PublishedServerEventHandlerRpcHandler.handleNode(PublishedServerEventHandlerRpcHandler.java:117)
	at com.vaadin.flow.server.communication.rpc.AbstractRpcInvocationHandler.handle(AbstractRpcInvocationHandler.java:64)
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleInvocationData(ServerRpcHandler.java:387)
	at com.vaadin.flow.server.communication.ServerRpcHandler.lambda$handleInvocations$1(ServerRpcHandler.java:368)
	at java.util.ArrayList.forEach(ArrayList.java:1251)
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:368)
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:310)
	at com.vaadin.flow.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:89)
	at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1507)
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:242)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:215)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.__doHandle(ContextHandler.java:1317)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:42020)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1219)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:219)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:531)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Received a sorters changed call from the client for a non-existent column
	at com.vaadin.flow.component.grid.Grid.sortersChanged(Grid.java:2791)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.__invoke(DelegatingMethodAccessorImpl.java:43)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:45009)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:45012)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.flow.server.communication.rpc.PublishedServerEventHandlerRpcHandler.invokeMethod(PublishedServerEventHandlerRpcHandler.java:167)
	... 49 more`

**Comment by mperktold** [comment]
In the meantime, we now use `Grid.addColumn`, `Grid.removeColumn`, and `Grid.setColumnOrder` to update the only those columns that actually changed.
That seems to improve things, but the error still appears from time to time.

**Comment by KasparScherrer** [comment]
I'm running into this issue as well, basically whenever i call `removeColumn` on a column that was sortable (and the user actually sorted it). The two workarounds suggested here aren't doing it for me. 

This leads to me creating a new instance of my grid whenever i would remove a column. I really don't like this. 
Therefore i wish the underlying bug would be fixed so that when I remove any column, the frontend-part stops trying to sort a column that no longer exists.

**Comment by tomivirkki** [comment]
The issue is likely caused by vaadin/vaadin-grid#1691

**Comment by szlac71** [comment]
for(Column<T> col : grid.getColumns()) {
					col.setSortable(false);
				}
				grid.sort(null);

**Comment by dskbrd** [comment]
I ran into the same problem when removing a sorted column and I think I found a possible workaround by manually clearing the "_sorters" referenced by the frontend-component before removing any column:

```java
// Clear any previous sorting
grid.sort(null);
// Explicilty clear sorting referenced in frontend
grid.getElement().executeJs("this._sorters = []");
// Remove column from grid
grid.removeColumnByKey(fieldName);
```

This seems to fix the issue but I am not yet sure what other side effects this may cause.

**Comment by cmrgKoradir** [comment]
@dskbrd I don't suppose you remember, but in case anybody _is_ reading this, **_is_** there a side-effect to this workaround we should be aware of?

Because as it turns out, we can still run into this in vaadin 24.2.

**Comment by web-padawan** [comment]
@cmrgKoradir If you have a code example to reproduce the problem, please submit a new issue and we will look into it.
Also please check if it's valid with a more recent version, preferably 24.4 or 24.3.
