### ISSUE TITLE
vaadin-grid breaks Polymer CLI build

### ISSUE THREAD

**Issue by vaadin-marcus** [vaadin/vaadin-grid#382]
Adding vaadin-grid to a Polymer CLI project (v 0.11.1) breaks the bundled build with the following exception:

```
error:   Uncaught exception: TypeError: Cannot read property 'is' of null
error:   TypeError: Cannot read property 'is' of null
    at Parser.parseDeclarationOrRuleset (/Users/mhellber/.nvm/versions/node/v6.0.0/lib/node_modules/polymer-cli/node_modules/shady-css-parser/dist/shady-css/parser.js:191:33)
    at Parser.parseRule (/Users/mhellber/.nvm/versions/node/v6.0.0/lib/node_modules/polymer-cli/node_modules/shady-css-parser/dist/shady-css/parser.js:80:21)
    at Parser.parseRules (/Users/mhellber/.nvm/versions/node/v6.0.0/lib/node_modules/polymer-cli/node_modules/shady-css-parser/dist/shady-css/parser.js:62:25)
    at Parser.parseStylesheet (/Users/mhellber/.nvm/versions/node/v6.0.0/lib/node_modules/polymer-cli/node_modules/shady-css-parser/dist/shady-css/parser.js:55:47)
    at Parser.parse (/Users/mhellber/.nvm/versions/node/v6.0.0/lib/node_modules/polymer-cli/node_modules/shady-css-parser/dist/shady-css/parser.js:51:19)
    at css (/Users/mhellber/.nvm/versions/node/v6.0.0/lib/node_modules/polymer-cli/node_modules/css-slam/index.js:51:39)
    at GulpTransform._transform (/Users/mhellber/.nvm/versions/node/v6.0.0/lib/node_modules/polymer-cli/node_modules/css-slam/index.js:69:36)
    at GulpTransform.Transform._read (_stream_transform.js:167:10)
    at GulpTransform.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:306:12)
    at writeOrBuffer (_stream_writable.js:292:5)
```

The issue is most likely in Polymer CLI, but adding a ticket here so we can track it and potentially help to get it sorted out. 

**Steps to reproduce**
1. Init a project with `polymer init app-drawer-template`
2. `bower install vaadin-grid`
3. Import and add Vaadin grid to `my-view1.html`
4. Run `polymer build`

**Comment by vaadin-marcus** [comment]
Looks like the `null` here is `currentToken` on https://github.com/PolymerLabs/shady-css-parser/blob/master/src/shady-css/parser.js#L183
