### ISSUE TITLE
error on build

### ISSUE THREAD

**Issue by misoucouma** [vaadin/vaadin-grid#403]
Hi, I am getting this error when trying to build: 
$ gulp gwt
[01:20:03] Working directory changed to F:\code\vaadin\vaadin-grid
[01:20:08] Using gulpfile F:\code\vaadin\vaadin-grid\gulpfile.js
[01:20:08] Starting 'gwt:clean'...
[01:20:08]  $ mvn -f,java,-B,clean,-q
[01:20:08] Starting 'gwt:hash:src'...
[01:20:08] Starting 'gwt:hash:js'...
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn mvn ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:968:3

**Comment by manolo** [comment]
Why do you need to compile the java source? have you modified something? The package is delivered with the compiled stuff `vaadin-grid.min.js`

If you need to build because you are changing java code, try this to see what is wrong in your setup:
```
  cd java
  mvn clean package -Pcompile
```

If it works, probably there is some problem in the gulp build script. We use linux or mac have not tested in windows.

**Comment by misoucouma** [comment]
Many thanks, I was having the same issue on Linux as well. now its working
