### ISSUE TITLE
Error Vulcanizing iron-list-behavior.html

### ISSUE THREAD

**Issue by MichaelAllenHardeman** [vaadin/vaadin-grid#699]
I have a large project based off a slightly older version of the Polymer Starter Kit. I want to use the vaadin-grid in this project, but trying to integrate it has cause some very difficult to solve errors to be thrown. I have created a [minimum example](https://github.com/MichaelAllenHardeman/miscellaneous/blob/master/vaadin-grid-vulcanization-error.zip?raw=true) based off [polymer starter kit version 1.3.0](https://github.com/PolymerElements/polymer-starter-kit/releases/download/v1.3.0/polymer-starter-kit-1.3.0.zip).

It is very difficult to exclude these files and not get some kind of console error when the app has loaded, and I haven't been able to do so yet. I have also tried doing things like converting the file with babel to es5, replacing certain text, wrapping the file. I'm not entirely sure why this error occurs on this file.

During the vulcanize task this stack trace is thrown:

```
(node:14856) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Error parsing scrip
    t in c:/minimum-example/app/bower_components/vaadin-grid/iron-list-behavior.html at NaN:NaN
    TypeError: Cannot read property 'push' of undefined
        at Object.behaviors (C:\minimum-example\node_modules\hydrolysis\lib\ast-utils\declaration-property-handlers.js:52:42
    )
        at Object.enterObjectExpression (C:\minimum-example\node_modules\hydrolysis\lib\ast-utils\behavior-finder.js:204:43)

        at applyVisitors (C:\minimum-example\node_modules\hydrolysis\lib\ast-utils\js-parse.js:31:51)
        at Controller.enter (C:\minimum-example\node_modules\hydrolysis\lib\ast-utils\js-parse.js:54:20)
        at Controller.__execute (C:\minimum-example\node_modules\estraverse\estraverse.js:395:31)
        at Controller.traverse (C:\minimum-example\node_modules\estraverse\estraverse.js:493:28)
        at Object.traverse (C:\minimum-example\node_modules\estraverse\estraverse.js:705:27)
        at Object.jsParse (C:\minimum-example\node_modules\hydrolysis\lib\ast-utils\js-parse.js:75:16)
        at Analyzer._processScript (C:\minimum-example\node_modules\hydrolysis\lib\analyzer.js:318:43)
        at C:\minimum-example\node_modules\hydrolysis\lib\analyzer.js:301:44
    (node:14856) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are
     not handled will terminate the Node.js process with a non-zero exit code.
    (node:14856) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: Error parsing scrip
    t in c:/minimum-example/app/bower_components/vaadin-grid/iron-list-behavior.html at NaN:NaN
    TypeError: Cannot read property 'push' of undefined
        at Object.behaviors (C:\minimum-example\node_modules\hydrolysis\lib\ast-utils\declaration-property-handlers.js:52:42
    )
        at Object.enterObjectExpression (C:\minimum-example\node_modules\hydrolysis\lib\ast-utils\behavior-finder.js:204:43)

        at applyVisitors (C:\minimum-example\node_modules\hydrolysis\lib\ast-utils\js-parse.js:31:51)
        at Controller.enter (C:\minimum-example\node_modules\hydrolysis\lib\ast-utils\js-parse.js:54:20)
        at Controller.__execute (C:\minimum-example\node_modules\estraverse\estraverse.js:395:31)
        at Controller.traverse (C:\minimum-example\node_modules\estraverse\estraverse.js:493:28)
        at Object.traverse (C:\minimum-example\node_modules\estraverse\estraverse.js:705:27)
        at Object.jsParse (C:\minimum-example\node_modules\hydrolysis\lib\ast-utils\js-parse.js:75:16)
        at Analyzer._processScript (C:\minimum-example\node_modules\hydrolysis\lib\analyzer.js:318:43)
        at C:\minimum-example\node_modules\hydrolysis\lib\analyzer.js:301:44
    (node:14856) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): Error in plugin 'gulp-vulc
    anize'
    Message:
        Error parsing script in c:/minimum-example/app/bower_components/vaadin-grid/iron-list-behavior.html at NaN:NaN
    TypeError: Cannot read property 'push' of undefined
        at Object.behaviors (C:\minimum-example\node_modules\hydrolysis\lib\ast-utils\declaration-property-handlers.js:52:42
    )
        at Object.enterObjectExpression (C:\minimum-example\node_modules\hydrolysis\lib\ast-utils\behavior-finder.js:204:43)

        at applyVisitors (C:\minimum-example\node_modules\hydrolysis\lib\ast-utils\js-parse.js:31:51)
        at Controller.enter (C:\minimum-example\node_modules\hydrolysis\lib\ast-utils\js-parse.js:54:20)
        at Controller.__execute (C:\minimum-example\node_modules\estraverse\estraverse.js:395:31)
        at Controller.traverse (C:\minimum-example\node_modules\estraverse\estraverse.js:493:28)
        at Object.traverse (C:\minimum-example\node_modules\estraverse\estraverse.js:705:27)
        at Object.jsParse (C:\minimum-example\node_modules\hydrolysis\lib\ast-utils\js-parse.js:75:16)
        at Analyzer._processScript (C:\minimum-example\node_modules\hydrolysis\lib\analyzer.js:318:43)
        at C:\minimum-example\node_modules\hydrolysis\lib\analyzer.js:301:44
    Details:
        location: [object Object]
        ownerDocument: c:/minimum-example/app/bower_components/vaadin-grid/iron-list-behavior.html
        fileName: C:\minimum-example\app\elements\elements.html
```

**Comment by Saulis** [comment]
Hi! Make sure you're using the latest `<vaadin-grid>` `v2.0.0-alpha2`

**Comment by MichaelAllenHardeman** [comment]
I tried with that version and it seems to vulcanize now.
