### ISSUE TITLE
Vaadin Grid is not compatible with visualforce when have remote objects

### ISSUE THREAD

**Issue by schmeisk** [vaadin/vaadin-grid#766]
I discover today that if I use remote objects on Visualforce the vadin-grid 1.2.1v does not work.
`<apex:remoteObjects>\n
    <apex:remoteObjectModel name="Example__c" jsShorthand="Example" fields="Id, Name"></apex:remoteObjectModel>
  </apex:remoteObjects>`
But the awesome part is, even if the vadin-grid has static data only, also does not work. And if I comment the remote objects tags, all works fine.
Error:

`Uncaught TypeError: Cannot read property 'a' of null
    at cp (/bower_components/vaadin-grid/vaadin-grid.min.js:546:222)
    at JF (/bower_components/vaadin-grid/vaadin-grid.min.js:548:51)
    at tF._.setLightDomTable (/bower_components/vaadin-grid/vaadin-grid.min.js:489:40)
    at HTMLElement.<anonymous> (/bower_components/vaadin-grid/vaadin-grid.html:1284:24)
    at Array.forEach (native)
    at HTMLElement.<anonymous> (/bower_components/vaadin-grid/vaadin-grid.html:1281:25)
    at DomApi.EffectiveNodesObserver._callListener (/bower_components/polymer/polymer-mini.html:1572:20)
    at DomApi.EffectiveNodesObserver._callListeners (/bower_components/polymer/polymer-mini.html:1538:6)
    at DomApi.EffectiveNodesObserver._notify (/bower_components/polymer/polymer-mini.html:1492:6)
    at Debouncer.complete (/bower_components/polymer/polymer-mini.html:2094:10)
    at Debouncer.boundComplete (/bower_components/polymer/polymer-mini.html:2071:6)
    at Object._atEndOfMicrotask (/bower_components/polymer/polymer-mini.html:2049:1)
    at MutationObserver.window.MutationObserver.observe.characterData (/bower_components/polymer/polymer-mini.html:2064:15)`

vaadin-grid used to test:

`<vaadin-grid>
        <table>
          <colgroup>
            <col/>
            <col/>
            <col/>
          </colgroup>
          <thead>
            <tr>
              <th>Name</th>
              <th>Value</th>
              <th>Progress</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Project A</td>
              <td>10000</td>
              <td>0.8</td>
            </tr>
            <tr>
              <td>Project B</td>
              <td>999999</td>
              <td>0.8</td>
            </tr>
          </tbody>
        </table>
      </vaadin-grid>`

**Comment by Saulis** [comment]
Hi!

Have you tried `v2.0.0-alpha2` ? https://github.com/vaadin/vaadin-grid/wiki/Migration-from-1.*-to-2.0

**Comment by schmeisk** [comment]
Hi Saulis, Thank you so much! Yes with the v2.0.0-alpha3 works perfectly. But, I'm curious to know why the 1.2.1v does not work.

**Comment by Saulis** [comment]
Hard to say without more information about your setup, but my guess is you've used Polymer's bindings inside the table cells – which don't work in `1.x`, but only in vaadin-grid `2.0`. You can read more about that here: https://github.com/vaadin/vaadin-grid/issues/380#issuecomment-224876764

**Comment by schmeisk** [comment]
The table does not had polymer bindings. The problem is with the remote object tags of the visualforce(Salesforce). Without the tags inside of the page works well. But with the remote objects tags does not.
